### ISSUE TITLE
Logo contribution

### ISSUE THREAD

**Issue by reallinfo** [codeaholicguy/halunar#1]
Hello @codeaholicguy 

i designed a logo for contribution. I designed a logo to make the application more recognizable. Is there anyone you like about these logos?  I will wait for feedback. 

Have a nice day.

![halunar](https://user-images.githubusercontent.com/36298335/42883146-6ade8afa-8aa3-11e8-8c23-f18f29932741.jpg)

**Comment by codeaholicguy** [comment]
Thanks <3. Could you please make a PR to update this logo in README file, and don't forget to add your name at Contributor section at the bottom, I very appreciate your work.

**Comment by reallinfo** [comment]
You're welcome, Ofcourse! I will send a pr and ı will send the all files.

Please tell me which one you prefer.

![halunar](https://user-images.githubusercontent.com/36298335/42890020-7a46f340-8ab4-11e8-8720-c886576c219f.jpg)

**Comment by codeaholicguy** [comment]
@reallinfo I think the dark colorway is better, but can we make the font a little bit elegant, or thinner?

**Comment by reallinfo** [comment]
Sure, How is these?

![h2](https://user-images.githubusercontent.com/36298335/42933249-05408af4-8b4d-11e8-810c-8b58617da8fd.jpg)

**Comment by reallinfo** [comment]
Also, especially if you have a font you want, I can apply it.

**Comment by codeaholicguy** [comment]
I love the second one, thanks so much. Just go ahead and make the PR.

**Comment by reallinfo** [comment]
You're welcome. I sent a pr. I added the all files. 

https://github.com/codeaholicguy/halunar/pull/2

**Comment by reallinfo** [comment]
If you / your friends need another logo, feel free to write to me. Have a nice day!

**Comment by codeaholicguy** [comment]
Thanks so much for your time.

**Comment by codeaholicguy** [comment]
@reallinfo Ah, if you don't mind, you can check this (https://github.com/codeaholicguy/wowcup) out, I am intending to change that to be a football cli.

**Comment by reallinfo** [comment]
Sure, no problem. I will give you feedback in the soon.
